version: "3.8"

services:
  app:
    build: .
    container_name: stock-management-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: MySql@VanTho0948
      DB_NAME: stock_management
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySql@VanTho0948
      MYSQL_DATABASE: stock_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
