import { Discount } from "@/types/Discount";
const sampleDisount: Discount[] = [
    {
        id: 'd1',
        name: 'Black Friday Sale',
        code: 'BF2024',
        description: 'Get 20% off all electronics for Black Friday!',
        type: 'PERCENTAGE',
        value: 20,
        discount_limit: '100 $',
        usage_limit: '50/100',
        order_minimum: '50 $',
        status: 'ACTIVE',
        start_time: '00:00',
        end_time: '23:59',
        start_date: '20/11/2024',
        end_date: '27/11/2024',
    },
    {
        id: 'd2',
        name: 'New Customer Welcome',
        code: 'WELCOME10',
        description: '10% off your first purchase.',
        type: 'PERCENTAGE',
        value: 10,
        discount_limit: '-',
        usage_limit: '150/200',
        order_minimum: '20 $',
        status: 'ACTIVE',
        start_time: '09:00',
        end_time: '17:00',
        start_date: '01/01/2024',
        end_date: '31/12/2024',
    },
    {
        id: 'd3',
        name: 'Holiday Savings',
        code: 'HOLIDAY5',
        description: 'Save $5 on orders over $75.',
        type: 'FIXED_AMOUNT',
        value: 5,
        discount_limit: '-',
        usage_limit: '0/50',
        order_minimum: '75 $',
        status: 'IN_ACTIVE',
        start_time: '00:00',
        end_time: '00:00',
        start_date: '15/12/2024',
        end_date: '31/12/2024',
    },
    {
        id: 'd4',
        name: 'Clearance Discount',
        code: 'CLEAR25',
        description: '25% off all clearance items.',
        type: 'PERCENTAGE',
        value: 25,
        discount_limit: '50 $',
        usage_limit: '10/10', // Fully used
        order_minimum: '-',
        status: 'IN_ACTIVE',
        start_time: '10:00',
        end_time: '22:00',
        start_date: '01/03/2024',
        end_date: '31/03/2024',
    },
    {
        id: 'd5',
        name: 'Loyalty Bonus',
        code: 'LOYALTY15',
        description: 'Special 15% discount for loyal customers.',
        type: 'PERCENTAGE',
        value: 15,
        discount_limit: '-',
        usage_limit: '25/50',
        order_minimum: '100 $',
        status: 'ACTIVE',
        start_time: '08:00',
        end_time: '20:00',
        start_date: '01/07/2024',
        end_date: '31/07/2024',
    },
    {
        id: 'd6',
        name: 'Flash Sale',
        code: 'FLASH10',
        description: 'Limited time $10 off on selected items.',
        type: 'FIXED_AMOUNT',
        value: 10,
        discount_limit: '10 $',
        usage_limit: '5/5', // Fully used
        order_minimum: '30 $',
        status: 'IN_ACTIVE',
        start_time: '14:00',
        end_time: '16:00',
        start_date: '05/08/2024',
        end_date: '05/08/2024',
    },
]

export default sampleDisount;